# Generated by Django 2.2.4 on 2019-08-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_auto_20190826_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='usuario',
            new_name='user',
        ),
    ]
